// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace PersonClass
{
	public class Person
	{
		private string name;
		private int? age;
		
		public Person (string name)
		{
			this.Name = name;
		}
		
		public Person (string name, int age)
		{
			this.Name = name;
			this.Age = age;
		}
		
		public string Name {
			get {
				return this.name;
			}
			set {
				if (string.IsNullOrEmpty (value)) {
					throw new ArgumentException ("Invalid Name");
				}
				this.name = value;
			}
		}
		
		public int? Age { get; set; }
		
		public override string ToString ()
		{
			return string.Format ("[Person: Name={0}, Age={1}]", Name, (Age == null ? "N/A" : Age.ToString ()));
		}
	}
}

